#!/usr/bin/env php
<?php

declare(strict_types=1);

use Ajo\Console;
use Ajo\Container;
use Ajo\Database;
use Ajo\Test;
use Ajo\Job;

require __DIR__ . '/vendor/autoload.php';

Console::use(fn() => Container::set('db', Database::get()));

Job::register(Console::instance());

Job::schedule('* * * * *', function () {
    Console::info('Sending pending emails...');
})
    ->name('emails.send')
    ->queue('emails')
    ->concurrency(3)
    ->priority(10);

Job::schedule('0 2 * * *', function () {
    Console::info('Daily report...');
    // ...
})
    ->name('report.daily')
    ->queue('reports')
    ->priority(50);

Test::register(Console::instance());

exit(Console::dispatch());
