#!/usr/bin/env php
<?php

declare(strict_types=1);

use Ajo\Console;
use Ajo\Container;
use Ajo\Database;
use Ajo\Test;
use Ajo\Job;

require __DIR__ . '/vendor/autoload.php';

Console::use(fn() => Container::set('db', Database::get()));

Job::register(Console::instance());

Job::schedule('emails.send', function () {
    Console::info('Sending pending emails...');
})
    ->everyFiveMinutes()
    ->queue('emails')
    ->concurrency(3)
    ->priority(10);

Job::schedule('report.daily', function () {
    Console::info('Daily report...');
})
    ->daily()
    ->hour(2)  // 2am
    ->month([1, 4, 7, 10])  // Run only in Jan, Apr, Jul, Oct
    ->queue('reports')
    ->priority(50);

Job::schedule('monitor.health', function () {
    Console::info('Health check...');
})
    ->everyTenSeconds()  // Sub-minute scheduling
    ->when(fn() => getenv('ENABLE_MONITORING') === 'true');

Test::register(Console::instance());

exit(Console::dispatch());
